package com.walmart.finance.ap.fds.receiving.validator;

public enum ReceivingInfoRequestCombinations {

    INVOICEID,
    VENDORNUMBER_PURCHASEORDERNUMBER_INVOICENUMBER,
    VENDORNUMBER_PURCHASEORDERNUMBER_RECEIPTNUMBERS,
    VENDORNUMBER_PURCHASEORDERNUMBER_LOCATIONNUMBER,
    VENDORNUMBER_LOCATIONNUMBER_INVOICENUMBER,
    VENDORNUMBER_LOCATIONNUMBER_RECEIPTNUMBERS,
    VENDORNUMBER_PURCHASEORDERID,
    LOCATIONNUMBER_PURCHASEORDERNUMBER_RECEIPTDATESTART_RECEIPTDATEEND,
    LOCATIONNUMBER_INVOICENUMBER_RECEIPTDATESTART_RECEIPTDATEEND,
    LOCATIONNUMBER_VENDORNUMBER_RECEIPTDATESTART_RECEIPTDATEEND,
    LOCATIONNUMBER_RECEIPTDATESTART_RECEIPTDATEEND,
    TRANSACTIONID_TRANSACTIONSEQNBR;
}
