package com.walmart.finance.ap.fds.receiving.validator;

public enum ReceivingInfoRequestCombinations {

    INVOICEID,
    VENDORNUMBER_PURCHASEORDERNUMBER_INVOICENUMBER,
    VENDORNUMBER_PURCHASEORDERNUMBER_RECEIPTNUMBERS,
    VENDORNUMBER_PURCHASEORDERNUMBER_LOCATIONNUMBER,
    VENDORNUMBER_LOCATIONNUMBER_INVOICENUMBER,
    VENDORNUMBER_LOCATIONNUMBER_RECEIPTNUMBERS,
    VENDORNUMBER_PURCHASEORDERID;
}
