tools:
  jdk:
    - 1.8
  maven:
    - 3.6.0
  sonarscanner:
    - 3.0.3.778

triggers:
  - manual:
      name: Release Image
      call: release

envs:
  global:
    variables:
      MAVEN_VERSION: ''
      MAVEN_GROUP_ID: ''
      MAVEN_ARTIFACT_ID: ''
      GIT_REVISION: ''
      devAcrName: 'apfsregistrydev.azurecr.io' #here goes your container registry name
      devAcrCred: 'c1f34f31-f988-49d1-b32a-a20de27cd559'
      releaseAcrName: 'apfsregistryrelease.azurecr.io' #here goes your container registry name
      releaseAcrCred: 'da462fd4-c11d-476b-9255-cd085d4de03e' #here goes your looper credential for the container registry

flows:

  default:
    - shell: echo "pushImageToDevRegistry"
    - call: readpom
    - mvn clean install
    - call: pushImageToDevRegistry

  pr:
    - mvn clean package

  # Expects version variable to be passed
  release:
    - shell: echo "Release Flow Called"
    - call: readpom
    - git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
    - git fetch --all
    - git checkout master
    - echo "release flow called with version $version"
    - mvn clean install
    - call: pushImageToReleaseRegistry

  pushImageToReleaseRegistry:
    - shell: echo "pushImageToReleaseRegistry"
    - shell: echo "${releaseAcrName}/${MAVEN_ARTIFACT_ID}:${version}"
    - node(docker-daemon):
        - dockerImage:
            tags:
              - '${releaseAcrName}/${MAVEN_ARTIFACT_ID}:${version}'
            push: true
            dockerfile: 'docker/Dockerfile'
            creds:
              apfsregistryrelease.azurecr.io: '${releaseAcrCred}'

  pushImageToDevRegistry:
    - shell: echo "pushImageToDevRegistry"
    - shell: echo "${devAcrName}/${MAVEN_ARTIFACT_ID}:${MAVEN_VERSION}"
    - node(docker-daemon):
        - dockerImage:
            tags:
              - '${devAcrName}/${MAVEN_ARTIFACT_ID}:${MAVEN_VERSION}'
            push: true
            dockerfile: 'docker/Dockerfile'
            creds:
              apfsregistrydev.azurecr.io: '${devAcrCred}'
  runsonar:
    - sonar("Sonar"):
        - (name sonar) sonar-scanner -Dproject.settings=sonar-project.properties
        - hygieia.publishSonar()

  hygieiaPublish:
    - hygieia.publishBuild()

  readpom:
    - exposeVars(maven)
    - echo "MAVEN_VERSION=${MAVEN_VERSION}"
    - echo "MAVEN_GROUP_ID=${MAVEN_GROUP_ID}"
    - echo "MAVEN_ARTIFACT_ID=${MAVEN_ARTIFACT_ID}"
    - echo "GIT_REVISION=${git-revision}"